<?php

namespace CBVehicles\API\GBFS;

//only makes sense after merging #2153
use CommonsBooking\Repository\Item;

class VehicleTypes extends \CommonsBooking\API\GBFS\BaseRoute {

	protected $rest_base = 'vehicle_types.json';
	protected $schemaUrl = CB_VEHICLES_PATH . 'vehicle_types.json';

	public function prepare_item_for_response( $item, $request ) {
		return parent::prepare_item_for_response( $item,
			$request ); // TODO: Change the autogenerated stub
	}

	protected static function getListName(): string {
		return 'vehicles';
	}


	protected static function getRepository(): PostRepository {
		// we iterate over posts with cb_item post type
		return new Item();
	}
}
